nb_snapshots = 20000
nb_components = 3 # velocity u, velocity v, velocity w
ng = [512, 128, 160] # dimensions of the velocity field
starting_x = 100
cutting_rate = 1
nb_width_points = 64
control_width = nb_width_points//cutting_rate
control_length = ng[1]//cutting_rate
nb_actions = control_width * control_length

starting_coeff = 2
nb_coeffs = 4
tke_ref = 0
gamma = 0.3
nb_epoch = 50
starting_blow = 0.4
max_blow = 0.8
blowstep = 0.1
alpha = 0.15
Nu_baseline = 2.962 # calculated and rounded from 2.9619621858466085 obtained from the baseline simulation with no control
P_base_pump = 0.061 # calculated and rounded from 0.060989 obtained from the calculus operated in the tmp.py file in the "P_base_pump computation" section
blow_area_rate = nb_width_points / ng[0]
learning_rate = 1e-6